[2023-12-09 03:01:31,381] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:01:31] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:01:31,557] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:01:31] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:02:50,108] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:02:50] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:03:25,238] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:03:25] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:07:09,093] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:07:29,216] WARNING download_csv() L67   Erro ao fazer download do CSV, Não foi possível baixar arquivo - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\app.py L67  
[2023-12-09 03:07:29,217] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:07:29] "[31m[1mGET /dataset/download HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:09:14,977] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:09:19,293] WARNING download_csv() L67   Erro ao fazer download do CSV, Não foi possível baixar arquivo - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\app.py L67  
[2023-12-09 03:09:19,294] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:09:19] "[31m[1mGET /dataset/download HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:14:12,275] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:14:16,066] WARNING download_csv() L58   Erro ao fazer download do Excel, Não foi possível baixar arquivo - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\app.py L58  
[2023-12-09 03:14:16,067] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:14:16] "[31m[1mGET /dataset/download HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:16:12,284] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:16:16,034] WARNING download_csv() L64   Erro ao fazer download do Excel, Não foi possível baixar arquivo - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\app.py L64  
[2023-12-09 03:16:16,036] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:16:16] "[31m[1mGET /dataset/download HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:16:37,216] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:16:38,476] WARNING download_csv() L67   Erro ao fazer download do Excel, Não foi possível baixar arquivo - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\app.py L67  
[2023-12-09 03:16:38,477] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:16:38] "[31m[1mGET /dataset/download HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:17:19,080] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:17:20,125] WARNING download_csv() L67   Erro ao fazer download do Excel, Não foi possível baixar arquivo - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\app.py L67  
[2023-12-09 03:17:20,126] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:17:20] "[31m[1mGET /dataset/download HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:19:51,880] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:19:55,447] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:19:55] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:20:01,491] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:20:01] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:25:51,637] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:25:51] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:26:29,495] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:26:29] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:27:53,408] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:27:53] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:28:12,035] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:28:12] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:29:25,928] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:29:25] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:31:16,175] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:31:23,670] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:31:23] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:32:46,804] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:32:46] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:34:54,116] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:35:01,401] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:35:01] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:35:13,351] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:35:13] "GET /dataset/download HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:36:35,729] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 03:36:38,677] ERROR log_exception() L1449 Exception on /dataset/download [GET] - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1747, in make_response
    rv.headers.update(headers)  # type: ignore[arg-type]
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\datastructures.py", line 1267, in update
    for key, value in mapping:
TypeError: 'Response' object is not iterable
[2023-12-09 03:36:38,680] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 03:36:38] "[35m[1mGET /dataset/download HTTP/1.1[0m" 500 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
